apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-helloworld
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - hello.test.domain.ca
    - hello.test.domain.ca:443
    port:
      name: https-helloworld
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
  - hosts:
    - hello.test.domain.ca
    - hello.test.domain.ca:80
    port:
      name: http-helloworld
      number: 80
      protocol: HTTP