apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: helloworld-grpc-notimeout-int
spec:
  destination:
    service: greeter-server.staging.svc.cluster.local|grpc-greeter
  match:
    request:
      headers:
        uri:
          prefix: "/"
  httpReqTimeout:
    simpleTimeout:
      timeout: 20s
